language: go

go:
  - 1.12.x

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      script:
        - go get golang.org/x/lint/golint
        - golint -set_exit_status
        - go vet -v
    - stage: test
      script:
        - go get golang.org/x/tools/cmd/cover
        - go get github.com/mattn/goveralls
        - go test -v -covermode=count -coverprofile=coverage.out
        - $GOPATH/bin/goveralls -service=travis-ci

matrix:
  allow_failures:
    - go: master
  fast_finish: true
