language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - master

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      script:
        - go get golang.org/x/lint/golint
        - go get golang.org/x/tools/cmd/cover
        - go get github.com/mattn/goveralls
        - golint -set_exit_status
        - go vet -v
    - stage: test
      script:
        - go test -v -covermode=count -coverprofile=coverage.out

matrix:
  allow_failures:
    - go: master
  fast_finish: true
